# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearningRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearningRxSwift
  pod 'Alamofire'

  pod 'RxSwift', '4.0.0'
  pod 'RxCocoa', '4.0.0'
#    pod 'RealmSwift', '3.0.2'
  pod 'RealmSwift'
  pod 'RxRealm', '0.7.4'
  pod 'Unbox', '2.5.0'
  pod 'Then', '2.2.1'
  pod 'Reachability', '3.2.0'
  pod 'Kingfisher', '4.2.0'
  pod 'RxRealmDataSources', '0.2.9'

  target 'LearningRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearningRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
